//
// Copyright 2024 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//

// WARNING: THIS FILE IS GENERATED BY usdGenSchema.  DO NOT EDIT.
TF_WRAP(UsdShadeNodeGraph);
TF_WRAP(UsdShadeMaterial);
TF_WRAP(UsdShadeShader);
TF_WRAP(UsdShadeNodeDefAPI);
TF_WRAP(UsdShadeConnectableAPI);
TF_WRAP(UsdShadeMaterialBindingAPI);
TF_WRAP(UsdShadeCoordSysAPI);
TF_WRAP(UsdShadeTokens);
