//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/backPlateSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdBackPlateSchemaTokens,
    HD_BACK_PLATE_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdVec2fDataSourceHandle
HdBackPlateSchema::GetScaleTweak() const
{
    return _GetTypedDataSource<HdVec2fDataSource>(
        HdBackPlateSchemaTokens->scaleTweak);
}

HdVec3fDataSourceHandle
HdBackPlateSchema::GetRotateXYZTweak() const
{
    return _GetTypedDataSource<HdVec3fDataSource>(
        HdBackPlateSchemaTokens->rotateXYZTweak);
}

HdVec3fDataSourceHandle
HdBackPlateSchema::GetTranslateTweak() const
{
    return _GetTypedDataSource<HdVec3fDataSource>(
        HdBackPlateSchemaTokens->translateTweak);
}

HdAssetPathDataSourceHandle
HdBackPlateSchema::GetImage() const
{
    return _GetTypedDataSource<HdAssetPathDataSource>(
        HdBackPlateSchemaTokens->image);
}

HdAssetPathDataSourceHandle
HdBackPlateSchema::GetAlphaImage() const
{
    return _GetTypedDataSource<HdAssetPathDataSource>(
        HdBackPlateSchemaTokens->alphaImage);
}

HdAssetPathDataSourceHandle
HdBackPlateSchema::GetDepthImage() const
{
    return _GetTypedDataSource<HdAssetPathDataSource>(
        HdBackPlateSchemaTokens->depthImage);
}

HdFloatDataSourceHandle
HdBackPlateSchema::GetDepthMinOffset() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdBackPlateSchemaTokens->depthMinOffset);
}

HdFloatDataSourceHandle
HdBackPlateSchema::GetDepthNormalizingFactor() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdBackPlateSchemaTokens->depthNormalizingFactor);
}

HdFloatDataSourceHandle
HdBackPlateSchema::GetDepthCameraSpaceOffset() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdBackPlateSchemaTokens->depthCameraSpaceOffset);
}

HdVec3fDataSourceHandle
HdBackPlateSchema::GetLumaSlope() const
{
    return _GetTypedDataSource<HdVec3fDataSource>(
        HdBackPlateSchemaTokens->lumaSlope);
}

HdVec3fDataSourceHandle
HdBackPlateSchema::GetLumaOffset() const
{
    return _GetTypedDataSource<HdVec3fDataSource>(
        HdBackPlateSchemaTokens->lumaOffset);
}

HdVec3fDataSourceHandle
HdBackPlateSchema::GetLumaPower() const
{
    return _GetTypedDataSource<HdVec3fDataSource>(
        HdBackPlateSchemaTokens->lumaPower);
}

HdTokenDataSourceHandle
HdBackPlateSchema::GetPlateVisibility() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        HdBackPlateSchemaTokens->plateVisibility);
}

/*static*/
HdContainerDataSourceHandle
HdBackPlateSchema::BuildRetained(
        const HdVec2fDataSourceHandle &scaleTweak,
        const HdVec3fDataSourceHandle &rotateXYZTweak,
        const HdVec3fDataSourceHandle &translateTweak,
        const HdAssetPathDataSourceHandle &image,
        const HdAssetPathDataSourceHandle &alphaImage,
        const HdAssetPathDataSourceHandle &depthImage,
        const HdFloatDataSourceHandle &depthMinOffset,
        const HdFloatDataSourceHandle &depthNormalizingFactor,
        const HdFloatDataSourceHandle &depthCameraSpaceOffset,
        const HdVec3fDataSourceHandle &lumaSlope,
        const HdVec3fDataSourceHandle &lumaOffset,
        const HdVec3fDataSourceHandle &lumaPower,
        const HdTokenDataSourceHandle &plateVisibility
)
{
    TfToken _names[13];
    HdDataSourceBaseHandle _values[13];

    size_t _count = 0;

    if (scaleTweak) {
        _names[_count] = HdBackPlateSchemaTokens->scaleTweak;
        _values[_count++] = scaleTweak;
    }

    if (rotateXYZTweak) {
        _names[_count] = HdBackPlateSchemaTokens->rotateXYZTweak;
        _values[_count++] = rotateXYZTweak;
    }

    if (translateTweak) {
        _names[_count] = HdBackPlateSchemaTokens->translateTweak;
        _values[_count++] = translateTweak;
    }

    if (image) {
        _names[_count] = HdBackPlateSchemaTokens->image;
        _values[_count++] = image;
    }

    if (alphaImage) {
        _names[_count] = HdBackPlateSchemaTokens->alphaImage;
        _values[_count++] = alphaImage;
    }

    if (depthImage) {
        _names[_count] = HdBackPlateSchemaTokens->depthImage;
        _values[_count++] = depthImage;
    }

    if (depthMinOffset) {
        _names[_count] = HdBackPlateSchemaTokens->depthMinOffset;
        _values[_count++] = depthMinOffset;
    }

    if (depthNormalizingFactor) {
        _names[_count] = HdBackPlateSchemaTokens->depthNormalizingFactor;
        _values[_count++] = depthNormalizingFactor;
    }

    if (depthCameraSpaceOffset) {
        _names[_count] = HdBackPlateSchemaTokens->depthCameraSpaceOffset;
        _values[_count++] = depthCameraSpaceOffset;
    }

    if (lumaSlope) {
        _names[_count] = HdBackPlateSchemaTokens->lumaSlope;
        _values[_count++] = lumaSlope;
    }

    if (lumaOffset) {
        _names[_count] = HdBackPlateSchemaTokens->lumaOffset;
        _values[_count++] = lumaOffset;
    }

    if (lumaPower) {
        _names[_count] = HdBackPlateSchemaTokens->lumaPower;
        _values[_count++] = lumaPower;
    }

    if (plateVisibility) {
        _names[_count] = HdBackPlateSchemaTokens->plateVisibility;
        _values[_count++] = plateVisibility;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

HdBackPlateSchema::Builder &
HdBackPlateSchema::Builder::SetScaleTweak(
    const HdVec2fDataSourceHandle &scaleTweak)
{
    _scaleTweak = scaleTweak;
    return *this;
}

HdBackPlateSchema::Builder &
HdBackPlateSchema::Builder::SetRotateXYZTweak(
    const HdVec3fDataSourceHandle &rotateXYZTweak)
{
    _rotateXYZTweak = rotateXYZTweak;
    return *this;
}

HdBackPlateSchema::Builder &
HdBackPlateSchema::Builder::SetTranslateTweak(
    const HdVec3fDataSourceHandle &translateTweak)
{
    _translateTweak = translateTweak;
    return *this;
}

HdBackPlateSchema::Builder &
HdBackPlateSchema::Builder::SetImage(
    const HdAssetPathDataSourceHandle &image)
{
    _image = image;
    return *this;
}

HdBackPlateSchema::Builder &
HdBackPlateSchema::Builder::SetAlphaImage(
    const HdAssetPathDataSourceHandle &alphaImage)
{
    _alphaImage = alphaImage;
    return *this;
}

HdBackPlateSchema::Builder &
HdBackPlateSchema::Builder::SetDepthImage(
    const HdAssetPathDataSourceHandle &depthImage)
{
    _depthImage = depthImage;
    return *this;
}

HdBackPlateSchema::Builder &
HdBackPlateSchema::Builder::SetDepthMinOffset(
    const HdFloatDataSourceHandle &depthMinOffset)
{
    _depthMinOffset = depthMinOffset;
    return *this;
}

HdBackPlateSchema::Builder &
HdBackPlateSchema::Builder::SetDepthNormalizingFactor(
    const HdFloatDataSourceHandle &depthNormalizingFactor)
{
    _depthNormalizingFactor = depthNormalizingFactor;
    return *this;
}

HdBackPlateSchema::Builder &
HdBackPlateSchema::Builder::SetDepthCameraSpaceOffset(
    const HdFloatDataSourceHandle &depthCameraSpaceOffset)
{
    _depthCameraSpaceOffset = depthCameraSpaceOffset;
    return *this;
}

HdBackPlateSchema::Builder &
HdBackPlateSchema::Builder::SetLumaSlope(
    const HdVec3fDataSourceHandle &lumaSlope)
{
    _lumaSlope = lumaSlope;
    return *this;
}

HdBackPlateSchema::Builder &
HdBackPlateSchema::Builder::SetLumaOffset(
    const HdVec3fDataSourceHandle &lumaOffset)
{
    _lumaOffset = lumaOffset;
    return *this;
}

HdBackPlateSchema::Builder &
HdBackPlateSchema::Builder::SetLumaPower(
    const HdVec3fDataSourceHandle &lumaPower)
{
    _lumaPower = lumaPower;
    return *this;
}

HdBackPlateSchema::Builder &
HdBackPlateSchema::Builder::SetPlateVisibility(
    const HdTokenDataSourceHandle &plateVisibility)
{
    _plateVisibility = plateVisibility;
    return *this;
}

HdContainerDataSourceHandle
HdBackPlateSchema::Builder::Build()
{
    return HdBackPlateSchema::BuildRetained(
        _scaleTweak,
        _rotateXYZTweak,
        _translateTweak,
        _image,
        _alphaImage,
        _depthImage,
        _depthMinOffset,
        _depthNormalizingFactor,
        _depthCameraSpaceOffset,
        _lumaSlope,
        _lumaOffset,
        _lumaPower,
        _plateVisibility
    );
}

/*static*/
HdBackPlateSchema
HdBackPlateSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdBackPlateSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdBackPlateSchemaTokens->backPlate))
        : nullptr);
}

/*static*/
const TfToken &
HdBackPlateSchema::GetSchemaToken()
{
    return HdBackPlateSchemaTokens->backPlate;
}

/*static*/
HdTokenDataSourceHandle
HdBackPlateSchema::BuildPlateVisibilityDataSource(
    const TfToken &plateVisibility)
{

    if (plateVisibility == HdBackPlateSchemaTokens->all) {
        static const HdRetainedTypedSampledDataSource<TfToken>::Handle ds =
            HdRetainedTypedSampledDataSource<TfToken>::New(plateVisibility);
        return ds;
    }
    if (plateVisibility == HdBackPlateSchemaTokens->solo) {
        static const HdRetainedTypedSampledDataSource<TfToken>::Handle ds =
            HdRetainedTypedSampledDataSource<TfToken>::New(plateVisibility);
        return ds;
    }
    if (plateVisibility == HdBackPlateSchemaTokens->none) {
        static const HdRetainedTypedSampledDataSource<TfToken>::Handle ds =
            HdRetainedTypedSampledDataSource<TfToken>::New(plateVisibility);
        return ds;
    }
    // fallback for unknown token
    return HdRetainedTypedSampledDataSource<TfToken>::New(plateVisibility);
} 

PXR_NAMESPACE_CLOSE_SCOPE