//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/extGpuSyncSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdExtGpuSyncSchemaTokens,
    HD_EXT_GPU_SYNC_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdTokenDataSourceHandle
HdExtGpuSyncSchema::GetBackendApi() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        HdExtGpuSyncSchemaTokens->backendApi);
}

HdUInt64DataSourceHandle
HdExtGpuSyncSchema::GetWriteSemaphore() const
{
    return _GetTypedDataSource<HdUInt64DataSource>(
        HdExtGpuSyncSchemaTokens->writeSemaphore);
}

HdUInt64DataSourceHandle
HdExtGpuSyncSchema::GetReadSemaphore() const
{
    return _GetTypedDataSource<HdUInt64DataSource>(
        HdExtGpuSyncSchemaTokens->readSemaphore);
}

HdUInt64DataSourceHandle
HdExtGpuSyncSchema::GetExternalWriteSemaphore() const
{
    return _GetTypedDataSource<HdUInt64DataSource>(
        HdExtGpuSyncSchemaTokens->externalWriteSemaphore);
}

HdUInt64DataSourceHandle
HdExtGpuSyncSchema::GetExternalReadSemaphore() const
{
    return _GetTypedDataSource<HdUInt64DataSource>(
        HdExtGpuSyncSchemaTokens->externalReadSemaphore);
}

HdTokenDataSourceHandle
HdExtGpuSyncSchema::GetHandleType() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        HdExtGpuSyncSchemaTokens->handleType);
}

HdTokenDataSourceHandle
HdExtGpuSyncSchema::GetKind() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        HdExtGpuSyncSchemaTokens->kind);
}

HdTokenDataSourceHandle
HdExtGpuSyncSchema::GetDeviceUuid() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        HdExtGpuSyncSchemaTokens->deviceUuid);
}

HdUInt64DataSourceHandle
HdExtGpuSyncSchema::GetLogicalDeviceId() const
{
    return _GetTypedDataSource<HdUInt64DataSource>(
        HdExtGpuSyncSchemaTokens->logicalDeviceId);
}

/*static*/
HdContainerDataSourceHandle
HdExtGpuSyncSchema::BuildRetained(
        const HdTokenDataSourceHandle &backendApi,
        const HdUInt64DataSourceHandle &writeSemaphore,
        const HdUInt64DataSourceHandle &readSemaphore,
        const HdUInt64DataSourceHandle &externalWriteSemaphore,
        const HdUInt64DataSourceHandle &externalReadSemaphore,
        const HdTokenDataSourceHandle &handleType,
        const HdTokenDataSourceHandle &kind,
        const HdTokenDataSourceHandle &deviceUuid,
        const HdUInt64DataSourceHandle &logicalDeviceId
)
{
    TfToken _names[9];
    HdDataSourceBaseHandle _values[9];

    size_t _count = 0;

    if (backendApi) {
        _names[_count] = HdExtGpuSyncSchemaTokens->backendApi;
        _values[_count++] = backendApi;
    }

    if (writeSemaphore) {
        _names[_count] = HdExtGpuSyncSchemaTokens->writeSemaphore;
        _values[_count++] = writeSemaphore;
    }

    if (readSemaphore) {
        _names[_count] = HdExtGpuSyncSchemaTokens->readSemaphore;
        _values[_count++] = readSemaphore;
    }

    if (externalWriteSemaphore) {
        _names[_count] = HdExtGpuSyncSchemaTokens->externalWriteSemaphore;
        _values[_count++] = externalWriteSemaphore;
    }

    if (externalReadSemaphore) {
        _names[_count] = HdExtGpuSyncSchemaTokens->externalReadSemaphore;
        _values[_count++] = externalReadSemaphore;
    }

    if (handleType) {
        _names[_count] = HdExtGpuSyncSchemaTokens->handleType;
        _values[_count++] = handleType;
    }

    if (kind) {
        _names[_count] = HdExtGpuSyncSchemaTokens->kind;
        _values[_count++] = kind;
    }

    if (deviceUuid) {
        _names[_count] = HdExtGpuSyncSchemaTokens->deviceUuid;
        _values[_count++] = deviceUuid;
    }

    if (logicalDeviceId) {
        _names[_count] = HdExtGpuSyncSchemaTokens->logicalDeviceId;
        _values[_count++] = logicalDeviceId;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

HdExtGpuSyncSchema::Builder &
HdExtGpuSyncSchema::Builder::SetBackendApi(
    const HdTokenDataSourceHandle &backendApi)
{
    _backendApi = backendApi;
    return *this;
}

HdExtGpuSyncSchema::Builder &
HdExtGpuSyncSchema::Builder::SetWriteSemaphore(
    const HdUInt64DataSourceHandle &writeSemaphore)
{
    _writeSemaphore = writeSemaphore;
    return *this;
}

HdExtGpuSyncSchema::Builder &
HdExtGpuSyncSchema::Builder::SetReadSemaphore(
    const HdUInt64DataSourceHandle &readSemaphore)
{
    _readSemaphore = readSemaphore;
    return *this;
}

HdExtGpuSyncSchema::Builder &
HdExtGpuSyncSchema::Builder::SetExternalWriteSemaphore(
    const HdUInt64DataSourceHandle &externalWriteSemaphore)
{
    _externalWriteSemaphore = externalWriteSemaphore;
    return *this;
}

HdExtGpuSyncSchema::Builder &
HdExtGpuSyncSchema::Builder::SetExternalReadSemaphore(
    const HdUInt64DataSourceHandle &externalReadSemaphore)
{
    _externalReadSemaphore = externalReadSemaphore;
    return *this;
}

HdExtGpuSyncSchema::Builder &
HdExtGpuSyncSchema::Builder::SetHandleType(
    const HdTokenDataSourceHandle &handleType)
{
    _handleType = handleType;
    return *this;
}

HdExtGpuSyncSchema::Builder &
HdExtGpuSyncSchema::Builder::SetKind(
    const HdTokenDataSourceHandle &kind)
{
    _kind = kind;
    return *this;
}

HdExtGpuSyncSchema::Builder &
HdExtGpuSyncSchema::Builder::SetDeviceUuid(
    const HdTokenDataSourceHandle &deviceUuid)
{
    _deviceUuid = deviceUuid;
    return *this;
}

HdExtGpuSyncSchema::Builder &
HdExtGpuSyncSchema::Builder::SetLogicalDeviceId(
    const HdUInt64DataSourceHandle &logicalDeviceId)
{
    _logicalDeviceId = logicalDeviceId;
    return *this;
}

HdContainerDataSourceHandle
HdExtGpuSyncSchema::Builder::Build()
{
    return HdExtGpuSyncSchema::BuildRetained(
        _backendApi,
        _writeSemaphore,
        _readSemaphore,
        _externalWriteSemaphore,
        _externalReadSemaphore,
        _handleType,
        _kind,
        _deviceUuid,
        _logicalDeviceId
    );
}

/*static*/
HdExtGpuSyncSchema
HdExtGpuSyncSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdExtGpuSyncSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdExtGpuSyncSchemaTokens->sync))
        : nullptr);
}

/*static*/
const TfToken &
HdExtGpuSyncSchema::GetSchemaToken()
{
    return HdExtGpuSyncSchemaTokens->sync;
}

/*static*/
const HdDataSourceLocator &
HdExtGpuSyncSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/*static*/
HdTokenDataSourceHandle
HdExtGpuSyncSchema::BuildBackendApiDataSource(
    const TfToken &backendApi)
{

    if (backendApi == HdExtGpuSyncSchemaTokens->GL) {
        static const HdRetainedTypedSampledDataSource<TfToken>::Handle ds =
            HdRetainedTypedSampledDataSource<TfToken>::New(backendApi);
        return ds;
    }
    if (backendApi == HdExtGpuSyncSchemaTokens->Vulkan) {
        static const HdRetainedTypedSampledDataSource<TfToken>::Handle ds =
            HdRetainedTypedSampledDataSource<TfToken>::New(backendApi);
        return ds;
    }
    if (backendApi == HdExtGpuSyncSchemaTokens->Metal) {
        static const HdRetainedTypedSampledDataSource<TfToken>::Handle ds =
            HdRetainedTypedSampledDataSource<TfToken>::New(backendApi);
        return ds;
    }
    // fallback for unknown token
    return HdRetainedTypedSampledDataSource<TfToken>::New(backendApi);
}

/*static*/
HdTokenDataSourceHandle
HdExtGpuSyncSchema::BuildHandleTypeDataSource(
    const TfToken &handleType)
{

    if (handleType == HdExtGpuSyncSchemaTokens->opaqueWin32) {
        static const HdRetainedTypedSampledDataSource<TfToken>::Handle ds =
            HdRetainedTypedSampledDataSource<TfToken>::New(handleType);
        return ds;
    }
    if (handleType == HdExtGpuSyncSchemaTokens->opaqueFd) {
        static const HdRetainedTypedSampledDataSource<TfToken>::Handle ds =
            HdRetainedTypedSampledDataSource<TfToken>::New(handleType);
        return ds;
    }
    // fallback for unknown token
    return HdRetainedTypedSampledDataSource<TfToken>::New(handleType);
}

/*static*/
HdTokenDataSourceHandle
HdExtGpuSyncSchema::BuildKindDataSource(
    const TfToken &kind)
{

    if (kind == HdExtGpuSyncSchemaTokens->binary) {
        static const HdRetainedTypedSampledDataSource<TfToken>::Handle ds =
            HdRetainedTypedSampledDataSource<TfToken>::New(kind);
        return ds;
    }
    if (kind == HdExtGpuSyncSchemaTokens->timeline) {
        static const HdRetainedTypedSampledDataSource<TfToken>::Handle ds =
            HdRetainedTypedSampledDataSource<TfToken>::New(kind);
        return ds;
    }
    // fallback for unknown token
    return HdRetainedTypedSampledDataSource<TfToken>::New(kind);
} 

PXR_NAMESPACE_CLOSE_SCOPE