//
// Copyright 2021 Pixar
//
// Licensed under the Apache License, Version 2.0 (the "Apache License")
// with the following modification; you may not use this file except in
// compliance with the Apache License and the following modification to it:
// Section 6. Trademarks. is deleted and replaced with:
//
// 6. Trademarks. This License does not grant permission to use the trade
//    names, trademarks, service marks, or product names of the Licensor
//    and its affiliates, except as required to comply with Section 4(c) of
//    the License and to reproduce the content of the NOTICE file.
//
// You may obtain a copy of the Apache License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the Apache License with the above modification is
// distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied. See the Apache License for the specific
// language governing permissions and limitations under the Apache License.
//
////////////////////////////////////////////////////////////////////////
// This file is generated by a script.  Do not edit directly.  Edit the
// schema.template.h file to make changes.

#ifndef PXR_IMAGING_HD_LEGACY_DISPLAY_STYLE_SCHEMA_H
#define PXR_IMAGING_HD_LEGACY_DISPLAY_STYLE_SCHEMA_H

#include "pxr/imaging/hd/schema.h" 

PXR_NAMESPACE_OPEN_SCOPE

//-----------------------------------------------------------------------------

#define HDLEGACYDISPLAYSTYLE_SCHEMA_TOKENS \
    (displayStyle) \
    (refineLevel) \
    (flatShadingEnabled) \
    (displacementEnabled) \
    (occludedSelectionShowsThrough) \
    (shadingStyle) \
    (reprSelector) \
    (cullStyle) \

TF_DECLARE_PUBLIC_TOKENS(HdLegacyDisplayStyleSchemaTokens,
    HDLEGACYDISPLAYSTYLE_SCHEMA_TOKENS);

//-----------------------------------------------------------------------------

class HdLegacyDisplayStyleSchema : public HdSchema
{
public:
    HdLegacyDisplayStyleSchema(HdContainerDataSourceHandle container)
    : HdSchema(container) {}

    //ACCESSORS

    HdIntDataSourceHandle GetRefineLevel();
    HdBoolDataSourceHandle GetFlatShadingEnabled();
    HdBoolDataSourceHandle GetDisplacementEnabled();
    HdBoolDataSourceHandle GetOccludedSelectionShowsThrough();
    HdTokenDataSourceHandle GetShadingStyle();
    HdTokenArrayDataSourceHandle GetReprSelector();
    HdTokenDataSourceHandle GetCullStyle();

    // RETRIEVING AND CONSTRUCTING

    static HdContainerDataSourceHandle
    BuildRetained(
        const HdIntDataSourceHandle &refineLevel,
        const HdBoolDataSourceHandle &flatShadingEnabled,
        const HdBoolDataSourceHandle &displacementEnabled,
        const HdBoolDataSourceHandle &occludedSelectionShowsThrough,
        const HdTokenDataSourceHandle &shadingStyle,
        const HdTokenArrayDataSourceHandle &reprSelector,
        const HdTokenDataSourceHandle &cullStyle
    );

    class Builder
    {
    public:
        Builder &SetRefineLevel(
            const HdIntDataSourceHandle &refineLevel);
        Builder &SetFlatShadingEnabled(
            const HdBoolDataSourceHandle &flatShadingEnabled);
        Builder &SetDisplacementEnabled(
            const HdBoolDataSourceHandle &displacementEnabled);
        Builder &SetOccludedSelectionShowsThrough(
            const HdBoolDataSourceHandle &occludedSelectionShowsThrough);
        Builder &SetShadingStyle(
            const HdTokenDataSourceHandle &shadingStyle);
        Builder &SetReprSelector(
            const HdTokenArrayDataSourceHandle &reprSelector);
        Builder &SetCullStyle(
            const HdTokenDataSourceHandle &cullStyle);

        HdContainerDataSourceHandle Build();

    private:
        HdIntDataSourceHandle _refineLevel;
        HdBoolDataSourceHandle _flatShadingEnabled;
        HdBoolDataSourceHandle _displacementEnabled;
        HdBoolDataSourceHandle _occludedSelectionShowsThrough;
        HdTokenDataSourceHandle _shadingStyle;
        HdTokenArrayDataSourceHandle _reprSelector;
        HdTokenDataSourceHandle _cullStyle;
    };

    static HdLegacyDisplayStyleSchema GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer);

    static const HdDataSourceLocator &GetDefaultLocator();

    static const HdDataSourceLocator &GetReprSelectorLocator();
    static const HdDataSourceLocator &GetCullStyleLocator();

};

PXR_NAMESPACE_CLOSE_SCOPE

#endif