//
// Copyright 2021 Pixar
//
// Licensed under the Apache License, Version 2.0 (the "Apache License")
// with the following modification; you may not use this file except in
// compliance with the Apache License and the following modification to it:
// Section 6. Trademarks. is deleted and replaced with:
//
// 6. Trademarks. This License does not grant permission to use the trade
//    names, trademarks, service marks, or product names of the Licensor
//    and its affiliates, except as required to comply with Section 4(c) of
//    the License and to reproduce the content of the NOTICE file.
//
// You may obtain a copy of the Apache License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the Apache License with the above modification is
// distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied. See the Apache License for the specific
// language governing permissions and limitations under the Apache License.
//
////////////////////////////////////////////////////////////////////////
// This file is generated by a script.  Do not edit directly.  Edit the
// schema.template.cpp file to make changes.

#include "pxr/imaging/hd/markupTextSchema.h"
#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"


PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdMarkupTextSchemaTokens,
    HDMARKUPTEXT_SCHEMA_TOKENS);


HdMarkupTextTopologySchema
HdMarkupTextSchema::GetTopology()
{
    return HdMarkupTextTopologySchema(_GetTypedDataSource<HdContainerDataSource>(
        HdMarkupTextSchemaTokens->topology));
}

/*static*/
HdContainerDataSourceHandle
HdMarkupTextSchema::BuildRetained(
        const HdContainerDataSourceHandle &topology)
{
    TfToken names[1];
    HdDataSourceBaseHandle values[1];

    size_t count = 0;
    if (topology) {
        names[count] = HdMarkupTextSchemaTokens->topology;
        values[count++] = topology;
    }

    return HdRetainedContainerDataSource::New(count, names, values);
}

/*static*/
HdMarkupTextSchema
HdMarkupTextSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdMarkupTextSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdMarkupTextSchemaTokens->markupText))
        : nullptr);
}

/*static*/
const HdDataSourceLocator &
HdMarkupTextSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(
        HdMarkupTextSchemaTokens->markupText
    );
    return locator;
} 
/*static*/
const HdDataSourceLocator &
HdMarkupTextSchema::GetTopologyLocator()
{
    static const HdDataSourceLocator locator(
        HdMarkupTextSchemaTokens->markupText,
        HdMarkupTextSchemaTokens->topology
    );
    return locator;
}


HdMarkupTextSchema::Builder &
HdMarkupTextSchema::Builder::SetTopology(
    const HdContainerDataSourceHandle &topology)
{
    _topology = topology;
    return *this;
}

HdContainerDataSourceHandle
HdMarkupTextSchema::Builder::Build()
{
    return HdMarkupTextSchema::BuildRetained(
        _topology
    );
}


PXR_NAMESPACE_CLOSE_SCOPE