//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#ifndef PXR_IMAGING_HD_RENDER_SETTING_DESCRIPTOR_SCHEMA_H
#define PXR_IMAGING_HD_RENDER_SETTING_DESCRIPTOR_SCHEMA_H

/// \file

#include "pxr/imaging/hd/api.h"

#include "pxr/imaging/hd/schema.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

// --(BEGIN CUSTOM CODE: Declares)--
// --(END CUSTOM CODE: Declares)--

#define HD_RENDER_SETTING_DESCRIPTOR_SCHEMA_TOKENS \
    (renderSettingDescriptor) \
    (name) \
    (defaultValue) \

TF_DECLARE_PUBLIC_TOKENS(HdRenderSettingDescriptorSchemaTokens, HD_API,
    HD_RENDER_SETTING_DESCRIPTOR_SCHEMA_TOKENS);

//-----------------------------------------------------------------------------


/// \class HdRenderSettingDescriptorSchema
///
/// Describes render setting advertised by a renderer through
/// HdRendererPlugin::GetSceneIndexCreateArgs, see
/// HdSceneIndexCreateArgsSchema::GetRenderSettings.
///
class HdRenderSettingDescriptorSchema : public HdSchema
{
public:
    /// \name Schema retrieval
    /// @{

    HdRenderSettingDescriptorSchema(HdContainerDataSourceHandle container)
      : HdSchema(container) {}

    /// Retrieves a container data source with the schema's default name token
    /// "renderSettingDescriptor" from the parent container and constructs a
    /// HdRenderSettingDescriptorSchema instance.
    /// Because the requested container data source may not exist, the result
    /// should be checked with IsDefined() or a bool comparison before use.
    HD_API
    static HdRenderSettingDescriptorSchema GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer);

    /// @}

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

    /// \name Member accessor
    /// @{

    /// Human-readable name of the render setting, suitable for display in a
    /// UI.
    HD_API
    HdStringDataSourceHandle GetName() const;

    HD_API
    HdSampledDataSourceHandle GetDefaultValue() const; 

    /// @}

    /// \name Schema location
    /// @{

    /// Returns a token where the container representing this schema is found in
    /// a container by default.
    HD_API
    static const TfToken &GetSchemaToken();

    /// @} 

    /// \name Schema construction
    /// @{

    /// \deprecated Use Builder instead.
    ///
    /// Builds a container data source which includes the provided child data
    /// sources. Parameters with nullptr values are excluded. This is a
    /// low-level interface. For cases in which it's desired to define
    /// the container with a sparse set of child fields, the Builder class
    /// is often more convenient and readable.
    HD_API
    static HdContainerDataSourceHandle
    BuildRetained(
        const HdStringDataSourceHandle &name,
        const HdSampledDataSourceHandle &defaultValue
    );

    /// \class HdRenderSettingDescriptorSchema::Builder
    /// 
    /// Utility class for setting sparse sets of child data source fields to be
    /// filled as arguments into BuildRetained. Because all setter methods
    /// return a reference to the instance, this can be used in the "builder
    /// pattern" form.
    class Builder
    {
    public:
        HD_API
        Builder &SetName(
            const HdStringDataSourceHandle &name);
        HD_API
        Builder &SetDefaultValue(
            const HdSampledDataSourceHandle &defaultValue);

        /// Returns a container data source containing the members set thus far.
        HD_API
        HdContainerDataSourceHandle Build();

    private:
        HdStringDataSourceHandle _name;
        HdSampledDataSourceHandle _defaultValue;

    };

    /// @}
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif