//
// Copyright 2025 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/usdImaging/usdSkelImaging/resolvedSkeletonSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(UsdSkelImagingResolvedSkeletonSchemaTokens,
    USD_SKEL_IMAGING_RESOLVED_SKELETON_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdMatrixDataSourceHandle
UsdSkelImagingResolvedSkeletonSchema::GetSkelLocalToCommonSpace() const
{
    return _GetTypedDataSource<HdMatrixDataSource>(
        UsdSkelImagingResolvedSkeletonSchemaTokens->skelLocalToCommonSpace);
}

HdMatrix4fArrayDataSourceHandle
UsdSkelImagingResolvedSkeletonSchema::GetSkinningTransforms() const
{
    return _GetTypedDataSource<HdMatrix4fArrayDataSource>(
        UsdSkelImagingResolvedSkeletonSchemaTokens->skinningTransforms);
}

HdTokenArrayDataSourceHandle
UsdSkelImagingResolvedSkeletonSchema::GetBlendShapes() const
{
    return _GetTypedDataSource<HdTokenArrayDataSource>(
        UsdSkelImagingResolvedSkeletonSchemaTokens->blendShapes);
}

HdFloatArrayDataSourceHandle
UsdSkelImagingResolvedSkeletonSchema::GetBlendShapeWeights() const
{
    return _GetTypedDataSource<HdFloatArrayDataSource>(
        UsdSkelImagingResolvedSkeletonSchemaTokens->blendShapeWeights);
}

HdVec2iArrayDataSourceHandle
UsdSkelImagingResolvedSkeletonSchema::GetBlendShapeRanges() const
{
    return _GetTypedDataSource<HdVec2iArrayDataSource>(
        UsdSkelImagingResolvedSkeletonSchemaTokens->blendShapeRanges);
}

/*static*/
HdContainerDataSourceHandle
UsdSkelImagingResolvedSkeletonSchema::BuildRetained(
        const HdMatrixDataSourceHandle &skelLocalToCommonSpace,
        const HdMatrix4fArrayDataSourceHandle &skinningTransforms,
        const HdTokenArrayDataSourceHandle &blendShapes,
        const HdFloatArrayDataSourceHandle &blendShapeWeights,
        const HdVec2iArrayDataSourceHandle &blendShapeRanges
)
{
    TfToken _names[5];
    HdDataSourceBaseHandle _values[5];

    size_t _count = 0;

    if (skelLocalToCommonSpace) {
        _names[_count] = UsdSkelImagingResolvedSkeletonSchemaTokens->skelLocalToCommonSpace;
        _values[_count++] = skelLocalToCommonSpace;
    }

    if (skinningTransforms) {
        _names[_count] = UsdSkelImagingResolvedSkeletonSchemaTokens->skinningTransforms;
        _values[_count++] = skinningTransforms;
    }

    if (blendShapes) {
        _names[_count] = UsdSkelImagingResolvedSkeletonSchemaTokens->blendShapes;
        _values[_count++] = blendShapes;
    }

    if (blendShapeWeights) {
        _names[_count] = UsdSkelImagingResolvedSkeletonSchemaTokens->blendShapeWeights;
        _values[_count++] = blendShapeWeights;
    }

    if (blendShapeRanges) {
        _names[_count] = UsdSkelImagingResolvedSkeletonSchemaTokens->blendShapeRanges;
        _values[_count++] = blendShapeRanges;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

UsdSkelImagingResolvedSkeletonSchema::Builder &
UsdSkelImagingResolvedSkeletonSchema::Builder::SetSkelLocalToCommonSpace(
    const HdMatrixDataSourceHandle &skelLocalToCommonSpace)
{
    _skelLocalToCommonSpace = skelLocalToCommonSpace;
    return *this;
}

UsdSkelImagingResolvedSkeletonSchema::Builder &
UsdSkelImagingResolvedSkeletonSchema::Builder::SetSkinningTransforms(
    const HdMatrix4fArrayDataSourceHandle &skinningTransforms)
{
    _skinningTransforms = skinningTransforms;
    return *this;
}

UsdSkelImagingResolvedSkeletonSchema::Builder &
UsdSkelImagingResolvedSkeletonSchema::Builder::SetBlendShapes(
    const HdTokenArrayDataSourceHandle &blendShapes)
{
    _blendShapes = blendShapes;
    return *this;
}

UsdSkelImagingResolvedSkeletonSchema::Builder &
UsdSkelImagingResolvedSkeletonSchema::Builder::SetBlendShapeWeights(
    const HdFloatArrayDataSourceHandle &blendShapeWeights)
{
    _blendShapeWeights = blendShapeWeights;
    return *this;
}

UsdSkelImagingResolvedSkeletonSchema::Builder &
UsdSkelImagingResolvedSkeletonSchema::Builder::SetBlendShapeRanges(
    const HdVec2iArrayDataSourceHandle &blendShapeRanges)
{
    _blendShapeRanges = blendShapeRanges;
    return *this;
}

HdContainerDataSourceHandle
UsdSkelImagingResolvedSkeletonSchema::Builder::Build()
{
    return UsdSkelImagingResolvedSkeletonSchema::BuildRetained(
        _skelLocalToCommonSpace,
        _skinningTransforms,
        _blendShapes,
        _blendShapeWeights,
        _blendShapeRanges
    );
}

/*static*/
UsdSkelImagingResolvedSkeletonSchema
UsdSkelImagingResolvedSkeletonSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return UsdSkelImagingResolvedSkeletonSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                UsdSkelImagingResolvedSkeletonSchemaTokens->resolvedSkeleton))
        : nullptr);
}

/*static*/
const TfToken &
UsdSkelImagingResolvedSkeletonSchema::GetSchemaToken()
{
    return UsdSkelImagingResolvedSkeletonSchemaTokens->resolvedSkeleton;
}

/*static*/
const HdDataSourceLocator &
UsdSkelImagingResolvedSkeletonSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdSkelImagingResolvedSkeletonSchema::GetSkelLocalToCommonSpaceLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdSkelImagingResolvedSkeletonSchemaTokens->skelLocalToCommonSpace);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdSkelImagingResolvedSkeletonSchema::GetSkinningTransformsLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdSkelImagingResolvedSkeletonSchemaTokens->skinningTransforms);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdSkelImagingResolvedSkeletonSchema::GetBlendShapesLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdSkelImagingResolvedSkeletonSchemaTokens->blendShapes);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdSkelImagingResolvedSkeletonSchema::GetBlendShapeWeightsLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdSkelImagingResolvedSkeletonSchemaTokens->blendShapeWeights);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdSkelImagingResolvedSkeletonSchema::GetBlendShapeRangesLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdSkelImagingResolvedSkeletonSchemaTokens->blendShapeRanges);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE
