//
// Copyright 2024 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
#include "pxr/usd/usdText/tokens.h"

PXR_NAMESPACE_OPEN_SCOPE

UsdTextTokensType::UsdTextTokensType() :
    atLeast("atLeast", TfToken::Immortal),
    bottom("bottom", TfToken::Immortal),
    bottomToTop("bottomToTop", TfToken::Immortal),
    center("center", TfToken::Immortal),
    centerTab("centerTab", TfToken::Immortal),
    columnAlignment("columnAlignment", TfToken::Immortal),
    columnHeight("columnHeight", TfToken::Immortal),
    columnOffset("columnOffset", TfToken::Immortal),
    columnStyleBinding("columnStyle:binding", TfToken::Immortal),
    columnWidth("columnWidth", TfToken::Immortal),
    decimalTab("decimalTab", TfToken::Immortal),
    distributed("distributed", TfToken::Immortal),
    exactly("exactly", TfToken::Immortal),
    firstLineIndent("firstLineIndent", TfToken::Immortal),
    justify("justify", TfToken::Immortal),
    layoutBaselineDirection("layout:baselineDirection", TfToken::Immortal),
    layoutLinesStackDirection("layout:linesStackDirection", TfToken::Immortal),
    left("left", TfToken::Immortal),
    leftIndent("leftIndent", TfToken::Immortal),
    leftTab("leftTab", TfToken::Immortal),
    leftToRight("leftToRight", TfToken::Immortal),
    lineSpace("lineSpace", TfToken::Immortal),
    lineSpaceType("lineSpaceType", TfToken::Immortal),
    margins("margins", TfToken::Immortal),
    markup("markup", TfToken::Immortal),
    markupLanguage("markupLanguage", TfToken::Immortal),
    markupPlain("markup:plain", TfToken::Immortal),
    mtext("mtext", TfToken::Immortal),
    multiple("multiple", TfToken::Immortal),
    paragraphAlignment("paragraphAlignment", TfToken::Immortal),
    paragraphSpace("paragraphSpace", TfToken::Immortal),
    paragraphStyleBinding("paragraphStyle:binding", TfToken::Immortal),
    pixel("pixel", TfToken::Immortal),
    plain("plain", TfToken::Immortal),
    primvarsBackgroundColor("primvars:backgroundColor", TfToken::Immortal),
    primvarsBackgroundOpacity("primvars:backgroundOpacity", TfToken::Immortal),
    publishingPoint("publishingPoint", TfToken::Immortal),
    right("right", TfToken::Immortal),
    rightIndent("rightIndent", TfToken::Immortal),
    rightTab("rightTab", TfToken::Immortal),
    rightToLeft("rightToLeft", TfToken::Immortal),
    tabStopPositions("tabStopPositions", TfToken::Immortal),
    tabStopTypes("tabStopTypes", TfToken::Immortal),
    textMetricsUnit("textMetricsUnit", TfToken::Immortal),
    top("top", TfToken::Immortal),
    topToBottom("topToBottom", TfToken::Immortal),
    upToImpl("upToImpl", TfToken::Immortal),
    worldUnit("worldUnit", TfToken::Immortal),
    ColumnStyle("ColumnStyle", TfToken::Immortal),
    ColumnStyleAPI("ColumnStyleAPI", TfToken::Immortal),
    MarkupText("MarkupText", TfToken::Immortal),
    ParagraphStyle("ParagraphStyle", TfToken::Immortal),
    ParagraphStyleAPI("ParagraphStyleAPI", TfToken::Immortal),
    TextLayoutAPI("TextLayoutAPI", TfToken::Immortal),
    allTokens({
        atLeast,
        bottom,
        bottomToTop,
        center,
        centerTab,
        columnAlignment,
        columnHeight,
        columnOffset,
        columnStyleBinding,
        columnWidth,
        decimalTab,
        distributed,
        exactly,
        firstLineIndent,
        justify,
        layoutBaselineDirection,
        layoutLinesStackDirection,
        left,
        leftIndent,
        leftTab,
        leftToRight,
        lineSpace,
        lineSpaceType,
        margins,
        markup,
        markupLanguage,
        markupPlain,
        mtext,
        multiple,
        paragraphAlignment,
        paragraphSpace,
        paragraphStyleBinding,
        pixel,
        plain,
        primvarsBackgroundColor,
        primvarsBackgroundOpacity,
        publishingPoint,
        right,
        rightIndent,
        rightTab,
        rightToLeft,
        tabStopPositions,
        tabStopTypes,
        textMetricsUnit,
        top,
        topToBottom,
        upToImpl,
        worldUnit,
        ColumnStyle,
        ColumnStyleAPI,
        MarkupText,
        ParagraphStyle,
        ParagraphStyleAPI,
        TextLayoutAPI
    })
{
}

TfStaticData<UsdTextTokensType> UsdTextTokens;

PXR_NAMESPACE_CLOSE_SCOPE
