
#ifndef HDPARTICLEFIELD_DEBUGCODES_H
#define HDPARTICLEFIELD_DEBUGCODES_H

#include <pxr/base/tf/debug.h>
#include <pxr/pxr.h>

PXR_NAMESPACE_OPEN_SCOPE

TF_DEBUG_CODES(HDPARTICLEFIELD_GENERAL);

PXR_NAMESPACE_CLOSE_SCOPE

#endif // HDPARTICLEFIELD_DEBUGCODES_H
