//
// Copyright 2016 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
#include "pxr/exec/execIr/tokens.h"

PXR_NAMESPACE_OPEN_SCOPE

ExecIrTokensType::ExecIrTokensType() :
    avarsDefaultSpace("avars:defaultSpace", TfToken::Immortal),
    avarsRotationOrder("avars:rotationOrder", TfToken::Immortal),
    avarsRspin("avars:rspin", TfToken::Immortal),
    avarsRx("avars:rx", TfToken::Immortal),
    avarsRy("avars:ry", TfToken::Immortal),
    avarsRz("avars:rz", TfToken::Immortal),
    avarsTx("avars:tx", TfToken::Immortal),
    avarsTy("avars:ty", TfToken::Immortal),
    avarsTz("avars:tz", TfToken::Immortal),
    avarsUnitScaleFactor("avars:unitScaleFactor", TfToken::Immortal),
    defaultRx("default:rx", TfToken::Immortal),
    defaultRy("default:ry", TfToken::Immortal),
    defaultRz("default:rz", TfToken::Immortal),
    defaultSpace("default:space", TfToken::Immortal),
    defaultTx("default:tx", TfToken::Immortal),
    defaultTy("default:ty", TfToken::Immortal),
    defaultTz("default:tz", TfToken::Immortal),
    guideDisplayColor("guide:displayColor", TfToken::Immortal),
    guideDisplayOpacity("guide:displayOpacity", TfToken::Immortal),
    guideLength("guide:length", TfToken::Immortal),
    inDefaultSpace("in:defaultSpace", TfToken::Immortal),
    inRotationOrder("in:rotationOrder", TfToken::Immortal),
    inRspin("in:rspin", TfToken::Immortal),
    inRx("in:rx", TfToken::Immortal),
    inRy("in:ry", TfToken::Immortal),
    inRz("in:rz", TfToken::Immortal),
    inTx("in:tx", TfToken::Immortal),
    inTy("in:ty", TfToken::Immortal),
    inTz("in:tz", TfToken::Immortal),
    outDefaultSpace("out:defaultSpace", TfToken::Immortal),
    outSpace("out:space", TfToken::Immortal),
    parentDefaultSpace("parent:defaultSpace", TfToken::Immortal),
    parentInDefaultSpace("parentIn:defaultSpace", TfToken::Immortal),
    parentInSpace("parentIn:space", TfToken::Immortal),
    parentSpace("parent:space", TfToken::Immortal),
    posedDefaultSpace("posed:defaultSpace", TfToken::Immortal),
    posedSpace("posed:space", TfToken::Immortal),
    restRx("rest:rx", TfToken::Immortal),
    restRy("rest:ry", TfToken::Immortal),
    restRz("rest:rz", TfToken::Immortal),
    restSpace("rest:space", TfToken::Immortal),
    restTx("rest:tx", TfToken::Immortal),
    restTy("rest:ty", TfToken::Immortal),
    restTz("rest:tz", TfToken::Immortal),
    rig1("rig1", TfToken::Immortal),
    rig1Space("rig1:space", TfToken::Immortal),
    rig2("rig2", TfToken::Immortal),
    rig2Space("rig2:space", TfToken::Immortal),
    switch_("switch", TfToken::Immortal),
    XYZ("XYZ", TfToken::Immortal),
    XZY("XZY", TfToken::Immortal),
    YXZ("YXZ", TfToken::Immortal),
    YZX("YZX", TfToken::Immortal),
    ZXY("ZXY", TfToken::Immortal),
    ZYX("ZYX", TfToken::Immortal),
    IrController("IrController", TfToken::Immortal),
    IrFkController("IrFkController", TfToken::Immortal),
    IrJointScope("IrJointScope", TfToken::Immortal),
    IrSwitchController("IrSwitchController", TfToken::Immortal),
    IrXformable("IrXformable", TfToken::Immortal),
    allTokens({
        avarsDefaultSpace,
        avarsRotationOrder,
        avarsRspin,
        avarsRx,
        avarsRy,
        avarsRz,
        avarsTx,
        avarsTy,
        avarsTz,
        avarsUnitScaleFactor,
        defaultRx,
        defaultRy,
        defaultRz,
        defaultSpace,
        defaultTx,
        defaultTy,
        defaultTz,
        guideDisplayColor,
        guideDisplayOpacity,
        guideLength,
        inDefaultSpace,
        inRotationOrder,
        inRspin,
        inRx,
        inRy,
        inRz,
        inTx,
        inTy,
        inTz,
        outDefaultSpace,
        outSpace,
        parentDefaultSpace,
        parentInDefaultSpace,
        parentInSpace,
        parentSpace,
        posedDefaultSpace,
        posedSpace,
        restRx,
        restRy,
        restRz,
        restSpace,
        restTx,
        restTy,
        restTz,
        rig1,
        rig1Space,
        rig2,
        rig2Space,
        switch_,
        XYZ,
        XZY,
        YXZ,
        YZX,
        ZXY,
        ZYX,
        IrController,
        IrFkController,
        IrJointScope,
        IrSwitchController,
        IrXformable
    })
{
}

TfStaticData<ExecIrTokensType> ExecIrTokens;

PXR_NAMESPACE_CLOSE_SCOPE
