//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/usdImaging/usdImaging/usdUpAxisSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(UsdImagingUsdUpAxisSchemaTokens,
    USD_IMAGING_USD_UP_AXIS_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdTokenDataSourceHandle
UsdImagingUsdUpAxisSchema::GetUpAxis() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        UsdImagingUsdUpAxisSchemaTokens->upAxis);
}

/*static*/
HdContainerDataSourceHandle
UsdImagingUsdUpAxisSchema::BuildRetained(
        const HdTokenDataSourceHandle &upAxis
)
{
    TfToken _names[1];
    HdDataSourceBaseHandle _values[1];

    size_t _count = 0;

    if (upAxis) {
        _names[_count] = UsdImagingUsdUpAxisSchemaTokens->upAxis;
        _values[_count++] = upAxis;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

UsdImagingUsdUpAxisSchema::Builder &
UsdImagingUsdUpAxisSchema::Builder::SetUpAxis(
    const HdTokenDataSourceHandle &upAxis)
{
    _upAxis = upAxis;
    return *this;
}

HdContainerDataSourceHandle
UsdImagingUsdUpAxisSchema::Builder::Build()
{
    return UsdImagingUsdUpAxisSchema::BuildRetained(
        _upAxis
    );
}

/*static*/
UsdImagingUsdUpAxisSchema
UsdImagingUsdUpAxisSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return UsdImagingUsdUpAxisSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                UsdImagingUsdUpAxisSchemaTokens->__usdUpAxis))
        : nullptr);
}

/*static*/
const TfToken &
UsdImagingUsdUpAxisSchema::GetSchemaToken()
{
    return UsdImagingUsdUpAxisSchemaTokens->__usdUpAxis;
}

/*static*/
const HdDataSourceLocator &
UsdImagingUsdUpAxisSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdImagingUsdUpAxisSchema::GetUpAxisLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdImagingUsdUpAxisSchemaTokens->upAxis);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE