//
// Copyright 2020 benmalartre
//
// Unlicensed
//
#include "pxr/imaging/plugin/LoFi/tokens.h"

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(LoFiTokens, LOFI_TOKENS);
TF_DEFINE_PUBLIC_TOKENS(LoFiRegistryTokens, LOFI_REGISTRY_TOKENS);
TF_DEFINE_PUBLIC_TOKENS(LoFiGLTokens, LOFI_GL_TOKENS);
TF_DEFINE_PUBLIC_TOKENS(LoFiBufferTokens, LOFI_BUFFER_TOKENS);
TF_DEFINE_PUBLIC_TOKENS(LoFiUniformTokens, LOFI_UNIFORM_TOKENS);
TF_DEFINE_PUBLIC_TOKENS(LoFiShaderTokens, LOFI_SHADER_TOKENS);

PXR_NAMESPACE_CLOSE_SCOPE

