on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: aswf/ci-usd:2019
  
    steps:
    - uses: actions/checkout@v2

    - name: Prepare ccache timestamp
      id: ccache_cache_keys
      shell: bash
      run: |
        echo "::set-output name=date::`date -u +'%Y-%m-%dT%H:%M:%SZ'`"
  
    - name: CCache
      id: ccache
      uses: actions/cache@v1
      with:
        path: /tmp/ccache
        key: ${{ runner.os }}-usd-ccache-${{ steps.ccache_cache_keys.outputs.date }}
        restore-keys: |
          ${{ runner.os }}-usd-ccache-

    - run: |
        set -ex
        source activate_ccache.sh
        export CCACHE_DIR=/tmp/ccache
        # Create ccache folder if it was not restored by cache task
        mkdir -p /tmp/ccache
  
        mkdir build
        cd build
        cmake \
            -DCMAKE_INSTALL_PREFIX=/usr/local \
            -DOPENEXR_LOCATION=/usr/local \
            -DPXR_BUILD_TESTS=ON \
            -DPXR_BUILD_ALEMBIC_PLUGIN=OFF \
            ..
        make -j4
        ccache --show-stats
        sudo make install
      id: build
      name: Build
      shell: bash

    - run:  |
        set -ex
        cd build

        # GitHub docker actions all run as the root user (Azure Pipeline does create a non-root user with sudo access)

        tests_that_fail_when_run_as_root='TfAtomicOfstreamWrapper|TfFileUtils|TfSafeOutputFile|testUsdUtilsStitchClips|testUsdEditFilePermissions1'
        tests_that_fail_without_gpu='testusdview.*|testUsdRecord.*|testUsdAppUtilsFrameRecorder'

        xvfb-run ctest -VV -E "$tests_that_fail_when_run_as_root|$tests_that_fail_without_gpu" -T test --output-on-failure
      id: test
      name: Test
      shell: bash

    - name: Upload test results
      uses: actions/upload-artifact@master
      with:
        name: ctest-results
        path: 'build/Testing/'
      # Use always() to always run this step to publish test results when there are test failures
      if: always()
